
import React, { useState, useEffect, useCallback } from 'react';
import { GoogleGenAI } from '@google/genai';
import { ScriptConfig } from './types';
import Sidebar from './components/Sidebar';
import EditorPreview from './components/EditorPreview';
import AIAssistant from './components/AIAssistant';

const DEFAULT_CONFIG: ScriptConfig = {
  faction: "BEAR",
  kaliText: "┌──(root㉿kali)-[/]\\n└─# ",
  nhPath: "/data/data/com.offsec.nhterm/files/usr/bin/kali",
  chrootDir: "/data/local/nhsystem/kalifs",
  scriptMode: 'full',
  architecture: 'arm64',
  metapackages: [],
};

const App: React.FC = () => {
  const [config, setConfig] = useState<ScriptConfig>(DEFAULT_CONFIG);
  const [generatedScript, setGeneratedScript] = useState<string>("");
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiResponse, setAiResponse] = useState<string | null>(null);

  const generateScriptContent = useCallback((cfg: ScriptConfig) => {
    const isUpdateMode = cfg.scriptMode === 'update';
    const chrootArchDir = `/data/local/nhsystem/kali-${cfg.architecture}`;

    const pathConsistencyBlock = isUpdateMode 
    ? `
# 3. Verify Existing Installation
echo "[*] Verifying existing chroot at $CHROOT_DIR..."
if ! su -c "[ -d $CHROOT_DIR ]"; then
    echo "[!] Error: Cannot find existing Kali chroot directory to update!"
    exit 1
fi
` 
    : `
# 3. Fix Path Consistency for ${cfg.architecture.toUpperCase()}
# Modern NetHunter uses architecture-specific dirs; we symlink to kalifs for compatibility
if [ ! -d "$CHROOT_DIR" ]; then
    if su -c "[ -d ${chrootArchDir} ]"; then
        echo "[*] Symlinking ${chrootArchDir} to $CHROOT_DIR..."
        su -c "ln -s ${chrootArchDir} $CHROOT_DIR"
    else
        echo "[!] Error: Kali chroot for ${cfg.architecture} not found at ${chrootArchDir}!"
        exit 1
    fi
fi
`;

    const metapackagesBlock = cfg.metapackages.length > 0 ? `
# 7. Install Metapackages (Optional)
echo "[*] Installing selected metapackages: ${cfg.metapackages.join(' ')}"
echo "[!] This may take a significant amount of time depending on your network speed."
INSTALL_CMD="apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ${cfg.metapackages.join(' ')}"
$MAGISK_BIN su --mount-master -c "chroot $CHROOT_DIR /bin/bash -c \\"$INSTALL_CMD\\""
` : `
# 7. No metapackages selected. Skipping installation.`;


    return `#!/data/data/com.termux/files/usr/bin/bash
# Mode: ${isUpdateMode ? 'Update Existing Install' : 'Full Installation'}
# Architecture: ${cfg.architecture}
# Optimized for Android 12/13/14 and Magisk v26+
# Generated by NetHunter Script Architect
set -e

# --- Variable Definitions ---
FACTION="${cfg.faction}"
CHROOT_DIR="${cfg.chrootDir}"
NH_PATH="${cfg.nhPath}"

echo "[*] Initializing Boot-kali-${isUpdateMode ? 'update' : 'install'} for Android 12+..."

# 1. Check for Root (Essential for Magisk operations)
if ! command -v su > /dev/null; then
    echo "[!] Error: Root not detected. Please run inside Termux with root access."
    exit 1
fi

# 2. Dynamic Magisk Detection
# Improved detection using the Magisk environment itself
MAGISK_BIN=$(su -c "magisk --path")/magisk
if [ -z "$MAGISK_BIN" ]; then MAGISK_BIN="/sbin/magisk"; fi
echo "[+] Using Magisk binary at: $MAGISK_BIN"
${pathConsistencyBlock}
# 4. Create an Advanced Launch Shim
# This handles the mounting of system filesystems required by Android 12+
echo "[*] Creating persistent Kali launcher..."
cat <<EOF >./kali_shim
#!/system/bin/sh
# Mount essential filesystems for modern Android compatibility
$MAGISK_BIN su --mount-master -c "
    mount -o remount,dev,suid /data
    mount -t proc proc $CHROOT_DIR/proc
    mount -t sysfs sysfs $CHROOT_DIR/sys
    mount -o bind /dev $CHROOT_DIR/dev
    mount -t devpts devpts $CHROOT_DIR/dev/pts
    
    # Enter Chroot with correct environment
    chroot $CHROOT_DIR /usr/bin/env -i \\
        HOME=/root \\
        TERM=\\$TERM \\
        PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \\
        /bin/bash -l
"
EOF

# Clean up and deploy shim
sed -i 's/\\r$//' ./kali_shim
chmod 755 ./kali_shim
su -c "cp ./kali_shim $NH_PATH"
su -c "chmod 755 $NH_PATH"
rm ./kali_shim

# 5. Inject Identity and Prompt
echo "[*] Applying Faction ($FACTION) and Prompt configuration..."
PROMPT_CMD="echo 'export PS1=\\"${cfg.kaliText.replace(/"/g, '\\"')}\\"' >> /root/.bashrc"
$MAGISK_BIN su --mount-master -c "chroot $CHROOT_DIR /bin/bash -c \\"$PROMPT_CMD\\""
$MAGISK_BIN su --mount-master -c "chroot $CHROOT_DIR /bin/bash -c \\"echo $FACTION > /etc/faction\\""

# 6. Apply Android 12+ Phantom Process Killer Fix
echo "[*] Checking for Android 12+ Phantom Process Killer optimizations..."

# Fix 1: settings_config_gravity_ignore_pull_res
CURRENT_GRAVITY_PULL=$(su -c "settings get global settings_config_gravity_ignore_pull_res" 2>/dev/null || echo "failed")
if [ "$CURRENT_GRAVITY_PULL" != "true" ]; then
    echo "[+] Applying gravity pull fix..."
    su -c "settings put global settings_config_gravity_ignore_pull_res true"
else
    echo "[*] Gravity pull fix already applied."
fi

# Fix 2: max_phantom_processes
CURRENT_PHANTOM_PROCS=$(su -c "/system/bin/device_config get activity_manager max_phantom_processes" 2>/dev/null || echo "failed")
if [ "$CURRENT_PHANTOM_PROCS" != "2147483647" ]; then
    echo "[+] Applying max phantom processes fix..."
    su -c "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"
else
    echo "[*] Max phantom processes fix already applied."
fi
${metapackagesBlock}

echo "------------------------------------------------------------"
echo "[+] Installation ${isUpdateMode ? 'update' : ''} complete."
echo "[+] Android 12+ specific optimizations have been checked and applied if necessary."
echo "------------------------------------------------------------"
`;
  }, []);

  useEffect(() => {
    setGeneratedScript(generateScriptContent(config));
  }, [config, generateScriptContent]);

  const handleAskAI = async (query: string) => {
    setIsAiLoading(true);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: `I am working with a Termux NetHunter Bash script. 
        Current Script: 
        \`\`\`bash
        ${generatedScript}
        \`\`\`
        
        Question: ${query}
        Please provide technical advice and explain how to improve the script for compatibility with modern Android versions.`,
      });
      setAiResponse(response.text || "No response received.");
    } catch (error) {
      setAiResponse(`Error connecting to Gemini: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setIsAiLoading(false);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([generatedScript], { type: 'text/x-shellscript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'boot-kali-install.sh';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-screen w-full bg-[#0a0a0c] overflow-hidden">
      {/* Sidebar - Controls */}
      <Sidebar config={config} setConfig={setConfig} onDownload={handleDownload} />

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col min-w-0 border-l border-zinc-800">
        <header className="h-16 flex items-center justify-between px-6 bg-[#0f0f12] border-b border-zinc-800">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-violet-600 rounded flex items-center justify-center">
              <i className="fa-solid fa-terminal text-white"></i>
            </div>
            <h1 className="text-xl font-bold tracking-tight text-white">Script <span className="text-violet-500">Architect</span></h1>
          </div>
          <div className="flex gap-2">
            <button 
              onClick={handleDownload}
              className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-sm font-medium rounded-lg transition-colors flex items-center gap-2"
            >
              <i className="fa-solid fa-download"></i>
              Export .sh
            </button>
          </div>
        </header>

        <div className="flex-1 flex overflow-hidden">
          {/* Editor Area */}
          <div className="flex-1 relative bg-[#0f0f12] overflow-auto">
            <EditorPreview script={generatedScript} />
          </div>

          {/* AI Assistant Panel */}
          <AIAssistant 
            onAsk={handleAskAI} 
            loading={isAiLoading} 
            response={aiResponse} 
            setResponse={setAiResponse} 
          />
        </div>
      </main>
    </div>
  );
};

export default App;
