import React, { useState, useEffect, useCallback } from 'react';
import { GoogleGenAI } from '@google/genai';
import { ScriptConfig } from './types';
import Sidebar from './components/Sidebar';
import EditorPreview from './components/EditorPreview';
import AIAssistant from './components/AIAssistant';

const DEFAULT_CONFIG: ScriptConfig = {
  faction: "BEAR",
  kaliText: "┌──(root㉿kali)-[/]\\\\n└─# ",
  nhPath: "/data/data/com.offsec.nhterm/files/usr/bin/kali",
  chrootDir: "/data/local/nhsystem/kalifs",
  scriptMode: 'full',
  architecture: 'arm64',
  metapackages: [],
  setSelinuxPermissive: false,
  forceDns: true,
  installKex: false,
};

const App: React.FC = () => {
  const [config, setConfig] = useState<ScriptConfig>(DEFAULT_CONFIG);
  const [generatedScript, setGeneratedScript] = useState<string>("");
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiResponse, setAiResponse] = useState<string | null>(null);

  const generateScriptContent = useCallback((cfg: ScriptConfig) => {
    const isUpdateMode = cfg.scriptMode === 'update';
    const chrootArchDir = `/data/local/nhsystem/kali-${cfg.architecture}`;

    const pathConsistencyBlock = isUpdateMode
      ? `
# 3. Verify Existing Installation
echo "[*] Verifying existing chroot at $CHROOT_DIR..."
if ! su -c "[ -d $CHROOT_DIR ]"; then
    echo "[!] Error: Cannot find existing Kali chroot directory to update!"
    exit 1
fi
`
      : `
# 3. Fix Path Consistency for ${cfg.architecture.toUpperCase()}
# Modern NetHunter uses architecture-specific dirs; we symlink to kalifs for compatibility
if [ ! -d "$CHROOT_DIR" ]; then
    if su -c "[ -d ${chrootArchDir} ]"; then
        echo "[*] Symlinking ${chrootArchDir} to $CHROOT_DIR..."
        su -c "ln -s ${chrootArchDir} $CHROOT_DIR"
    else
        echo "[!] Error: Kali chroot for ${cfg.architecture} not found at ${chrootArchDir}!"
        exit 1
    fi
fi
`;
    
    const packagesToInstall = [...cfg.metapackages];
    if (cfg.installKex) {
        packagesToInstall.push('kali-win-kex');
    }

    const metapackagesBlock = packagesToInstall.length > 0 ? `
# 7. Install Metapackages & Add-ons
echo "[*] Installing selected packages: ${packagesToInstall.join(' ')}"
echo "[!] This may take a significant amount of time depending on your network speed."
INSTALL_CMD="apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ${packagesToInstall.join(' ')}"
su -mm -c "chroot $CHROOT_DIR /bin/bash -c \\"$INSTALL_CMD\\""
` : `
# 7. No metapackages or add-ons selected. Skipping installation.`;

    const selinuxBlock = cfg.setSelinuxPermissive ? `
# 8. Set SELinux to Permissive
echo "[*] Attempting to set SELinux to Permissive mode..."
if su -c "getenforce" | grep -q "Enforcing"; then
    su -c "setenforce 0"
    echo "[+] SELinux is now in Permissive mode."
else
    echo "[*] SELinux is already Permissive or unsupported."
fi
` : '# 8. SELinux mode unchanged.';

    const dnsBlock = cfg.forceDns ? `
# 9. Force DNS Resolver
echo "[*] Forcing DNS to 8.8.8.8 to prevent connectivity issues..."
DNS_CMD="echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
su -mm -c "chroot $CHROOT_DIR /bin/bash -c \\"$DNS_CMD\\""
` : '# 9. DNS resolver unchanged.';

    const kexPostInstallMessage = cfg.installKex ? `
echo "---"
echo "[!] Kali KeX was installed. To use it:"
echo "    1. Run 'kali' to enter the chroot."
echo "    2. Run 'kex passwd' to set your password."
echo "    3. Run 'kex' to start the server and follow the instructions."
` : '';


    return `#!/data/data/com.termux/files/usr/bin/env bash
# Mode: ${isUpdateMode ? 'Update Existing Install' : 'Full Installation'}
# Architecture: ${cfg.architecture}
# Optimized for Android 14/15 and Magisk v30+
# Generated by NetHunter Script Architect
set -e

# --- Variable Definitions ---
FACTION="${cfg.faction}"
CHROOT_DIR="${cfg.chrootDir}"
NH_PATH="${cfg.nhPath}"

echo "[*] Initializing Boot-kali-${isUpdateMode ? 'update' : 'install'} for Android 14+..."

# 1. Check for Root (Essential for Magisk operations)
if ! command -v su > /dev/null; then
    echo "[!] Error: Root not detected. Please run inside Termux with root access."
    exit 1
fi

# 2. Modern Magisk Detection (v26-v30+)
# Locates the binary via 'which' or falls back to the standard internal path.
MAGISK_PATH=$(su -c "which magisk")
if [ -z "$MAGISK_PATH" ]; then
    MAGISK_PATH="/data/adb/magisk/magisk" 
fi
echo "[+] Magisk binary identified at: $MAGISK_PATH"
${pathConsistencyBlock}
# 4. Create an Advanced, Namespace-Aware Launch Shim
# Uses 'su -mm' to enter the global mount namespace, ensuring mounts persist.
echo "[*] Creating persistent, namespace-aware Kali launcher..."
cat <<EOF >./kali_shim
#!/system/bin/sh
# This shim uses 'su -mm' to ensure mounts are globally visible and persistent.
$MAGISK_PATH su -mm -c "
    # Ensure /data is executable
    mount -o remount,dev,suid /data
    
    # Mount core filesystems idempotently (only if not already mounted)
    [ ! -d $CHROOT_DIR/proc/1 ] && mount -t proc proc $CHROOT_DIR/proc
    [ ! -d $CHROOT_DIR/sys/kernel ] && mount -t sysfs sysfs $CHROOT_DIR/sys
    [ ! -d $CHROOT_DIR/dev/pts ] && mount -o bind /dev $CHROOT_DIR/dev
    [ ! -c $CHROOT_DIR/dev/pts/0 ] && mount -t devpts devpts $CHROOT_DIR/dev/pts
    
    # Critical for Android 13+: Fix shared memory for tools like Metasploit
    mount -t tmpfs tmpfs $CHROOT_DIR/dev/shm -o rw,nosuid,nodev,noexec,mode=1777

    # Enter Chroot with correct environment
    chroot $CHROOT_DIR /usr/bin/env -i \\
        HOME=/root \\
        TERM=\\$TERM \\
        PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \\
        /bin/bash -l
"
EOF

# Clean up and deploy shim
sed -i 's/\\r$//' ./kali_shim
chmod 755 ./kali_shim
su -c "cp ./kali_shim $NH_PATH"
su -c "chmod 755 $NH_PATH"
rm ./kali_shim

# 5. Inject Identity and Prompt (using global namespace)
echo "[*] Applying Faction ($FACTION) and Prompt configuration..."
PROMPT_CMD="echo 'export PS1=\\"${cfg.kaliText.replace(/"/g, '\\"')}\\"' >> /root/.bashrc"
su -mm -c "chroot $CHROOT_DIR /bin/bash -c \\"$PROMPT_CMD\\""
su -mm -c "chroot $CHROOT_DIR /bin/bash -c \\"echo $FACTION > /etc/faction\\""

# 6. Apply Advanced Android 14+ Phantom Process Killer Fix
echo "[*] Applying Android 14+ Phantom Process Killer optimizations..."
su -c "settings put global settings_config_gravity_ignore_pull_res true"
su -c "device_config put activity_manager max_phantom_processes 2147483647"
su -c "device_config put activity_manager enable_phantom_process_killer false"

${metapackagesBlock}
${selinuxBlock}
${dnsBlock}

echo "------------------------------------------------------------"
echo "[+] Installation ${isUpdateMode ? 'update' : ''} complete."
echo "[+] Android 14+ specific optimizations have been applied."
echo "[+] Tip: For best results on Android 14, also check 'Disable child process restrictions' in Developer Options."
${kexPostInstallMessage}
echo "------------------------------------------------------------"
`;
  }, []);

  useEffect(() => {
    setGeneratedScript(generateScriptContent(config));
  }, [config, generateScriptContent]);

  const handleAskAI = async (query: string) => {
    setIsAiLoading(true);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
      const fullPrompt = `You are an expert assistant for the "NetHunter Script Architect" application. Your expertise covers the entire Kali Linux ecosystem, including NetHunter on Android (with Termux and Magisk) and desktop installations on platforms like Windows 11 using WSL.

A user is generating a script with the following configuration:
\`\`\`json
${JSON.stringify(config, null, 2)}
\`\`\`

And here is the script generated from that configuration: 
\`\`\`bash
${generatedScript}
\`\`\`

The user's question is: "${query}"

Please answer the user's question. If it's about the script, use the provided context. If it's a more general question (like installing Kali on a PC), provide a helpful, accurate guide for that specific topic.`;
      
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: fullPrompt,
      });
      setAiResponse(response.text || "No response received.");
    } catch (error) {
      setAiResponse(`Error connecting to Gemini: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setIsAiLoading(false);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([generatedScript], { type: 'text/x-shellscript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'boot-kali-install.sh';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex h-screen w-full bg-[#0a0a0c] overflow-hidden">
      {/* Sidebar - Controls */}
      <Sidebar config={config} setConfig={setConfig} onDownload={handleDownload} />

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col min-w-0 border-l border-zinc-800">
        <header className="h-16 flex items-center justify-between px-6 bg-[#0f0f12] border-b border-zinc-800">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-violet-600 rounded flex items-center justify-center">
              <i className="fa-solid fa-terminal text-white"></i>
            </div>
            <h1 className="text-xl font-bold tracking-tight text-white">Script <span className="text-violet-500">Architect</span></h1>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-sm font-medium rounded-lg transition-colors flex items-center gap-2"
            >
              <i className="fa-solid fa-download"></i>
              Export .sh
            </button>
          </div>
        </header>

        <div className="flex-1 flex overflow-hidden">
          {/* Editor Area */}
          <div className="flex-1 relative bg-[#0f0f12] overflow-auto">
            <EditorPreview script={generatedScript} />
          </div>

          {/* AI Assistant Panel */}
          <AIAssistant
            onAsk={handleAskAI}
            loading={isAiLoading}
            response={aiResponse}
            setResponse={setAiResponse}
          />
        </div>
      </main>
    </div>
  );
};

export default App;
